# permissions for end users to edit locusttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locusttest-editor-role
rules:
- apiGroups:
  - tests.lokust.io
  resources:
  - locusttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.lokust.io
  resources:
  - locusttests/status
  verbs:
  - get
