# permissions for end users to view locusttests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locusttest-viewer-role
rules:
- apiGroups:
  - tests.lokust.io
  resources:
  - locusttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.lokust.io
  resources:
  - locusttests/status
  verbs:
  - get
