/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/luizbafilho/lokust/apis/loadtests/v1beta1"
	scheme "github.com/luizbafilho/lokust/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocustTestsGetter has a method to return a LocustTestInterface.
// A group's client should implement this interface.
type LocustTestsGetter interface {
	LocustTests(namespace string) LocustTestInterface
}

// LocustTestInterface has methods to work with LocustTest resources.
type LocustTestInterface interface {
	Create(*v1beta1.LocustTest) (*v1beta1.LocustTest, error)
	Update(*v1beta1.LocustTest) (*v1beta1.LocustTest, error)
	UpdateStatus(*v1beta1.LocustTest) (*v1beta1.LocustTest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.LocustTest, error)
	List(opts v1.ListOptions) (*v1beta1.LocustTestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.LocustTest, err error)
	LocustTestExpansion
}

// locustTests implements LocustTestInterface
type locustTests struct {
	client rest.Interface
	ns     string
}

// newLocustTests returns a LocustTests
func newLocustTests(c *LoadtestsV1beta1Client, namespace string) *locustTests {
	return &locustTests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the locustTest, and returns the corresponding locustTest object, and an error if there is any.
func (c *locustTests) Get(name string, options v1.GetOptions) (result *v1beta1.LocustTest, err error) {
	result = &v1beta1.LocustTest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("locusttests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocustTests that match those selectors.
func (c *locustTests) List(opts v1.ListOptions) (result *v1beta1.LocustTestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.LocustTestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("locusttests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested locustTests.
func (c *locustTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("locusttests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a locustTest and creates it.  Returns the server's representation of the locustTest, and an error, if there is any.
func (c *locustTests) Create(locustTest *v1beta1.LocustTest) (result *v1beta1.LocustTest, err error) {
	result = &v1beta1.LocustTest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("locusttests").
		Body(locustTest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a locustTest and updates it. Returns the server's representation of the locustTest, and an error, if there is any.
func (c *locustTests) Update(locustTest *v1beta1.LocustTest) (result *v1beta1.LocustTest, err error) {
	result = &v1beta1.LocustTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("locusttests").
		Name(locustTest.Name).
		Body(locustTest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *locustTests) UpdateStatus(locustTest *v1beta1.LocustTest) (result *v1beta1.LocustTest, err error) {
	result = &v1beta1.LocustTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("locusttests").
		Name(locustTest.Name).
		SubResource("status").
		Body(locustTest).
		Do().
		Into(result)
	return
}

// Delete takes name of the locustTest and deletes it. Returns an error if one occurs.
func (c *locustTests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("locusttests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *locustTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("locusttests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched locustTest.
func (c *locustTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.LocustTest, err error) {
	result = &v1beta1.LocustTest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("locusttests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
