apiVersion: tests.lokust.io/v1beta1
kind: LocustTest
metadata:
  name: locusttest-sample
spec:
  # Add fields here
  replicas: 4
  resources:
    requests:
      memory: "300Mi"
      cpu: "1000m"
    limits:
      memory: "600Mi"
      cpu: "1000m"
